version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:<< parameters.python >>
    working_directory: ~/repo
    parameters:
      python:
        type: string
      django:
        type: string
    steps:
      - checkout
      - run: pip install tox
      - run: tox -e "py$(echo '<< parameters.python >>' | tr -d '.')-django<< parameters.django >>"

workflows:
  default-workflow:
    jobs:
      - test:
          matrix:
            parameters:
              python: ["3.6", "3.7", "3.8", "3.9"]
              django: ["22", "30", "31"]
